Add a k-d tree implementation, and integrate it with Hdbscan and KNN.
oracle/tribuo pull request #231
Opened 2022-04-20 18:58 UTC by geoffreydstewart

### Description
This PR introduces a k-d tree implementation, which can be used for nearest neighbour queries, and integrates this feature with Hdbscan and KNN. Initial performance measurements demonstrate that this k-d tree implementation is, in general, much faster than using a brute-force approach for larger datasets.

After these changes have been reviewed, there is a required change to the Hdbscan tutorial that will be made.

This PR supersedes #230 which contains a lot of interesting code review discussion, but was closed as the result of the branch being recreate. 

### Motivation
K-d trees can provide faster nearest neighbour queries compared to a brute-force technique. This results in faster model training times.

### Paper reference
This is the original paper which proposes a k-d tree:
J.L. Bentley "Multidimensional Binary Search Trees Used for Associative Searching", Commun. ACM, Vol 18, Sept. 1975, 509–517

2022-04-22 15:45 UTC, Craigacp requested changes
I'd like to properly nail down the semantics of the k-d tree building (which may just be documentation fixes now), and there are a couple of other small points.

2022-04-22 15:45 UTC, Craigacp commented on Math/src/main/java/org/tribuo/math/neighbour/kdtree/KDTree.java
> +     * on the left. The operation is performed for a specific dimension of the vectors defined by the comparator.
I think this should say "on the right" as the values less than are on the left.

2022-04-22 15:45 UTC, Craigacp commented on Math/src/main/java/org/tribuo/math/neighbour/kdtree/KDTree.java
> +            if (compareByDimension(points[idx], pivot, dimension) <= 0) {
Shouldn't this be a strict less than? The docs say it's less than on the left and greater than or equal on the right.

2022-04-22 15:45 UTC, Craigacp commented on Math/src/main/java/org/tribuo/math/neighbour/kdtree/KDTree.java
> +     * (with higher index) will be >= median, again not sorted. The order of the array will almost certainly be changed.
So this says that values equal to the median can be found on both sides of the tree, but that seems to conflict with the documented behaviour of the `partitionOnIndex` function (though not its actual behaviour).

2022-04-22 15:45 UTC, Craigacp commented on Math/src/main/java/org/tribuo/math/neighbour/kdtree/KDTree.java
> +        return new ArrayList<>(Arrays.asList(indexDistancePairListArray));
I think you missed converting this over to just returning `Arrays.asList`.

2022-04-22 22:48 UTC, geoffreydstewart commented on Clustering/Hdbscan/src/test/java/org/tribuo/clustering/hdbscan/TestHdbscan.java
> +        HdbscanTrainer trainer = new HdbscanTrainer(7, DistanceType.L2, 7,4, NeighboursQueryFactoryType.BRUTE_FORCE);
Yes, it's good to demonstrate the programatic execution path. For the tutorial update, II think 'll use an enum constant.

2022-04-22 22:49 UTC, geoffreydstewart commented on Math/src/main/java/org/tribuo/math/neighbour/NeighboursQueryFactory.java
> +    DistanceType getDistanceType();
Sure, let's avoid that breaking change later.

2022-04-22 22:57 UTC, geoffreydstewart commented on Math/src/main/java/org/tribuo/math/neighbour/kdtree/KDTreeFactory.java
> +        this.numThreads = numThreads;
Yep, added the `postConfig`s and quick corresponding tests for bad config case.

2022-04-25 18:58 UTC, Craigacp approved these changes
LGTM

2022-04-25 18:58 UTC, Craigacp commented on Clustering/Hdbscan/src/test/java/org/tribuo/clustering/hdbscan/TestHdbscan.java
> +        HdbscanTrainer trainer = new HdbscanTrainer(7, DistanceType.L2, 7,4, NeighboursQueryFactoryType.BRUTE_FORCE);
Sure, that's fine. I've hit issues where different constructors cause different failures so I like to exercise each base constructor when testing now.

2022-04-25 18:59 UTC, merged