Create javadoc for all classes in ModelCard package
oracle/tribuo pull request #250
Opened 2022-07-12 06:18 UTC by rmahinpei

### Description
- Create javadoc for all classes in ModelCard package.

2022-07-14 13:51 UTC, Craigacp requested changes
Overall this is good, I've made a few comments for a couple of extra things I'd like to see in there.

2022-07-14 13:51 UTC, Craigacp commented on Interop/ModelCard/src/main/java/org/tribuo/interop/modelcard/ModelCard.java
> +     * <p>
This comment should note that no metrics are extracted.

2022-07-14 13:51 UTC, Craigacp commented on Interop/ModelCard/src/main/java/org/tribuo/interop/modelcard/ModelCard.java
> +     * <p>
This should note that there are no usage details in the model card.

2022-07-14 13:51 UTC, Craigacp commented on Interop/ModelCard/src/main/java/org/tribuo/interop/modelcard/ModelCard.java
> +     * <p>
This should note that there are no metrics or usage details.

2022-07-14 13:51 UTC, Craigacp commented on Interop/ModelCard/src/main/java/org/tribuo/interop/modelcard/ModelCard.java
> +     * @return The {@link UsageDetails} of the ModelCard object.
Might be worth noting that this can be null.

2022-07-14 13:51 UTC, Craigacp commented on Interop/ModelCard/src/main/java/org/tribuo/interop/modelcard/ModelCardCLI.java
> +     * Starta the command shell
Typo "Starta".

2022-07-14 13:51 UTC, Craigacp commented on Interop/ModelCard/src/main/java/org/tribuo/interop/modelcard/ModelCardCLI.java
> +     * Throws {@link IOException} if a problem is encountered when processing Json content.
processing json content or actually reading/writing the file.

2022-07-14 13:51 UTC, Craigacp commented on Interop/ModelCard/src/main/java/org/tribuo/interop/modelcard/ModelCard.java
> + * all external models.
Can you cite the model card paper here?

2022-07-14 13:51 UTC, Craigacp commented on Interop/ModelCard/src/main/java/org/tribuo/interop/modelcard/package-info.java
> + * ModelCard feature to allow more transparent model reporting.
I think it might be nice to paste in an example model card in json format here so people get the idea, along with a citation to the model card paper.

2022-07-16 23:06 UTC, rmahinpei commented
Thank you for the comments. I've now addressed them all.

2022-07-17 14:55 UTC, Craigacp commented on Interop/ModelCard/src/main/java/org/tribuo/interop/modelcard/package-info.java
> + * {
Can you surround this with `<pre>` tags? Otherwise it'll render it as plain text and reformat it into a paragraph.

2022-07-17 14:57 UTC, Craigacp commented on Interop/ModelCard/src/main/java/org/tribuo/interop/modelcard/ModelCard.java
> + * Refer to <a href="https://arxiv.org/abs/1810.03993">Model Cards for Model Reporting</a> to read the original paper.
Can you use this citation style here and in the package-info - https://github.com/oracle/tribuo/blob/main/Classification/XGBoost/src/main/java/org/tribuo/classification/xgboost/XGBoostClassificationTrainer.java#L51. You can put a link in as well, but I prefer to have a more academic citation style for references than a plain link.

2022-07-18 01:08 UTC, rmahinpei commented
Thank you - I fixed those issues!

2022-07-18 02:17 UTC, Craigacp approved these changes
LGTM, thanks.

2022-07-18 02:17 UTC, merged